#!/bin/bash

# Installs tm20.ppd driver
# Tested as working under Ubuntu 14.04

cp rastertozj /usr/lib/cups/filter/
mkdir -p /usr/share/cups/model/zjiang
cp tm20.ppd /usr/share/cups/model/zjiang/
cd /usr/lib/cups/filter
chmod 755 rastertozj
chown root:root rastertozj
